stages:
  - build
  - test
  - deploy

services:
  - docker:19.03.12

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker-compose build
  tags:
    - docker

test:
  stage: test
  script:
    - docker-compose up -d
    - docker-compose exec backend npm test
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - echo "Deploying to production server..."
  only:
    - master
  tags:
    - docker
